/*  BEGIN_FILE_HDR
********************************************************************************
*   File Name       : Dem_PBcfg.c
********************************************************************************
*   Project/Product : AUTOSAR BSW PROJECT
*   Title           : Dem module configuration File
*   Author          : Hirain
********************************************************************************
*   Description     : Dem module configuration File
*
********************************************************************************
*   Limitations     : None
*
********************************************************************************
*
* END_FILE_HDR*/

/*******************************************************************************
*   Include files
*******************************************************************************/
#include "Dem_Lcfg.h"
#include "Rte_Dem.h"
#include "Dem_PBcfg.h"


/*******************************************************************************
*   Dem Container:DemConfigSet
*******************************************************************************/
#define DEM_START_SEC_CONFIG_DATA
#include "Dem_MemMap.h"


/*DemEventParameter*/
STATIC CONST(Dem_EventParameterType, DEM_CONST) Dem_EventTable_PB0[20] =
{
    {
        0,
        0,
        0,
        &(Dem_EnConditionGroupTable[1]),
        1,
        Cfg_D_Event_0x800116,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[1]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        1,
        &(Dem_EnConditionGroupTable[1]),
        1,
        Cfg_D_Event_0x800117,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[1]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        2,
        &(Dem_EnConditionGroupTable[3]),
        1,
        Cfg_D_Event_0x9C0119,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[2]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        3,
        &(Dem_EnConditionGroupTable[3]),
        1,
        Cfg_D_Event_0x9C0218,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[3]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        4,
        &(Dem_EnConditionGroupTable[6]),
        1,
        Cfg_D_Event_0x9C0311,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[4]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        5,
        &(Dem_EnConditionGroupTable[6]),
        1,
        Cfg_D_Event_0x9C0415,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[4]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        6,
        &(Dem_EnConditionGroupTable[6]),
        1,
        Cfg_D_Event_0x9C0511,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[5]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        7,
        &(Dem_EnConditionGroupTable[6]),
        1,
        Cfg_D_Event_0x9C0615,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[5]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        8,
        &(Dem_EnConditionGroupTable[3]),
        1,
        Cfg_D_Event_0x9D0119,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[2]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        9,
        &(Dem_EnConditionGroupTable[3]),
        1,
        Cfg_D_Event_0x9D0218,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[2]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        10,
        &(Dem_EnConditionGroupTable[4]),
        1,
        Cfg_D_Event_0x9D0319,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[2]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        11,
        &(Dem_EnConditionGroupTable[4]),
        1,
        Cfg_D_Event_0x9D0418,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[2]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        12,
        NULL_PTR,
        1,
        Cfg_D_Event_0x9D0511,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_D_Event_0x9D0511_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        13,
        NULL_PTR,
        1,
        Cfg_D_Event_0x9D0615,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_D_Event_0x9D0615_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        14,
        &(Dem_EnConditionGroupTable[0]),
        1,
        Cfg_D_Event_0xC00B88,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[0]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        15,
        &(Dem_EnConditionGroupTable[2]),
        1,
        Cfg_D_Event_0xF13C87,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_D_Event_0xF13C87_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        16,
        &(Dem_EnConditionGroupTable[2]),
        1,
        Cfg_D_Event_0xF1D187,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_D_Event_0xF1D187_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        17,
        &(Dem_EnConditionGroupTable[2]),
        1,
        Cfg_D_Event_0xF1D287,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_D_Event_0xF1D287_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        18,
        &(Dem_EnConditionGroupTable[2]),
        1,
        Cfg_D_Event_0xF3A987,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_D_Event_0xF3A987_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        19,
        &(Dem_EnConditionGroupTable[2]),
        1,
        Cfg_D_Event_0xF3B287,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_D_Event_0xF3B287_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    }
};
STATIC CONST(Dem_EventParameterType, DEM_CONST) Dem_EventTable_PB1[20] =
{
    {
        0,
        0,
        0,
        &(Dem_EnConditionGroupTable[1]),
        1,
        Cfg_P_Event_0x800116,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[1]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        1,
        &(Dem_EnConditionGroupTable[1]),
        1,
        Cfg_P_Event_0x800117,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[1]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        2,
        &(Dem_EnConditionGroupTable[5]),
        1,
        Cfg_P_Event_0x9C0119,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[2]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        3,
        &(Dem_EnConditionGroupTable[5]),
        1,
        Cfg_P_Event_0x9C0218,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[3]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        4,
        &(Dem_EnConditionGroupTable[6]),
        1,
        Cfg_P_Event_0x9C0311,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[4]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        5,
        &(Dem_EnConditionGroupTable[6]),
        1,
        Cfg_P_Event_0x9C0415,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[4]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        6,
        &(Dem_EnConditionGroupTable[7]),
        1,
        Cfg_P_Event_0x9C0511,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[5]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        7,
        &(Dem_EnConditionGroupTable[7]),
        1,
        Cfg_P_Event_0x9C0615,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[5]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        8,
        &(Dem_EnConditionGroupTable[3]),
        1,
        Cfg_P_Event_0x9D0119,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[2]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        9,
        &(Dem_EnConditionGroupTable[3]),
        1,
        Cfg_P_Event_0x9D0218,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[2]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        10,
        &(Dem_EnConditionGroupTable[4]),
        1,
        Cfg_P_Event_0x9D0319,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[2]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        11,
        &(Dem_EnConditionGroupTable[4]),
        1,
        Cfg_P_Event_0x9D0418,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[2]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        12,
        &(Dem_EnConditionGroupTable[6]),
        1,
        Cfg_P_Event_0x9D0511,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_P_Event_0x9D0511_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        13,
        &(Dem_EnConditionGroupTable[6]),
        1,
        Cfg_P_Event_0x9D0615,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_P_Event_0x9D0615_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        14,
        &(Dem_EnConditionGroupTable[0]),
        1,
        Cfg_P_Event_0xC00B88,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            &(Dem_DebounceTimeBaseClassTable[0]),
            NULL_PTR
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        15,
        &(Dem_EnConditionGroupTable[2]),
        1,
        Cfg_P_Event_0xF13C87,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_P_Event_0xF13C87_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        16,
        &(Dem_EnConditionGroupTable[2]),
        1,
        Cfg_P_Event_0xF1D387,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_P_Event_0xF1D387_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        17,
        &(Dem_EnConditionGroupTable[2]),
        1,
        Cfg_P_Event_0xF1D487,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_P_Event_0xF1D487_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        18,
        &(Dem_EnConditionGroupTable[2]),
        1,
        Cfg_P_Event_0xF3A987,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_P_Event_0xF3A987_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        0,
        0,
        19,
        &(Dem_EnConditionGroupTable[2]),
        1,
        Cfg_P_Event_0xF3B287,
        DEM_EVENT_KIND_SWC,
        FALSE,
        0,
        DEM_REPORT_AFTER_INIT,
        STANDARD_REPORTING,
        {
            NULL_PTR,
            NULL_PTR,
            &Dem_Rte_Cfg_P_Event_0xF3B287_GetFaultDetectionCounter
        },
        {
            NULL_PTR,
            DEM_NO_STATUS_BYTE_CHANGE
        },
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    }
};
/*DemDTC*/
STATIC CONST(Dem_DTCInfoType, DEM_CONST) Dem_DTCTable_PB0[20] =
{
    {
        (Dem_EventIdType)Cfg_D_Event_0x800116,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x800116,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0x800117,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x800117,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0x9C0119,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9C0119,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0x9C0218,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9C0218,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0x9C0311,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9C0311,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0x9C0415,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9C0415,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0x9C0511,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9C0511,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0x9C0615,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9C0615,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0x9D0119,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9D0119,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0x9D0218,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9D0218,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0x9D0319,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9D0319,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0x9D0418,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9D0418,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0x9D0511,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9D0511,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0x9D0615,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9D0615,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0xC00B88,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xC00B88,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0xF13C87,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xF13C87,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0xF1D187,
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xF1D187,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0xF1D287,
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xF1D287,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0xF3A987,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xF3A987,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_D_Event_0xF3B287,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xF3B287,
        DURING_SHUTDOWN,
    }
};
STATIC CONST(Dem_DTCInfoType, DEM_CONST) Dem_DTCTable_PB1[20] =
{
    {
        (Dem_EventIdType)Cfg_P_Event_0x800116,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x800116,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0x800117,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x800117,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0x9C0119,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9C0119,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0x9C0218,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9C0218,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0x9C0311,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9C0311,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0x9C0415,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9C0415,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0x9C0511,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9C0511,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0x9C0615,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9C0615,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0x9D0119,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9D0119,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0x9D0218,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9D0218,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0x9D0319,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9D0319,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0x9D0418,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9D0418,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0x9D0511,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9D0511,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0x9D0615,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0x9D0615,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0xC00B88,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xC00B88,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0xF13C87,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xF13C87,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0xF1D387,
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xF1D387,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0xF1D487,
        1,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xF1D487,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0xF3A987,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xF3A987,
        DURING_SHUTDOWN,
    },
    {
        (Dem_EventIdType)Cfg_P_Event_0xF3B287,
        0,
        0,
        DEM_SEVERITY_NO_SEVERITY,
        0xF3B287,
        DURING_SHUTDOWN,
    }
};
/*DemPidClass*/

CONST(Dem_ConfigType,DEM_CONST) Dem_PBCfgSet[2] =
{
    {
        20,
        20,
        Dem_EventTable_PB0,
        Dem_DTCTable_PB0,
    },
    {
        20,
        20,
        Dem_EventTable_PB1,
        Dem_DTCTable_PB1,
    }
};

#define DEM_STOP_SEC_CONFIG_DATA
#include "Dem_MemMap.h"




